### ISSUE TITLE
[Proposed] Addition - Taskade 

### ISSUE THREAD

**Issue by johnxie** [brettkromkamp/awesome-knowledge-management#16]
Consider adding: [Taskade](https://taskade.com)

Hi all, John here, co-founder and CEO of Taskade, a real-time collaborative outliner for tasks, notes, that is project-driven in a tree and hierarchical structure. Hope you will consider including Taskade in the list. I sent a PR here https://github.com/brettkromkamp/awesome-knowledge-management/pull/15

Thanks

**Comment by brettkromkamp** [comment]
Nice-looking application. Added it to the list.

**Comment by johnxie** [comment]
thanks!
