### ISSUE TITLE
[Proposed Addition] mindlib (mindlib.de).

### ISSUE THREAD

**Issue by navigator8** [brettkromkamp/awesome-knowledge-management#18]
Organize your knowledge with your personal thought library!

Instead of writing knowledge into your memory by repeating it many times, you can store it in a network of information with mindlib. In just one action and without the risk of forgetting it again.

Starting from a central entry point, information can be saved, linked and compared with mindlib. Knowledge is displayed in a mind map-like style and information can be linked with one another as required.

To support the creation and insertion of information, mindlib offers itself as a share target for web links, uses Open-Graph to retrieve information from URLs and integrates the Google Knowledge Graph to search for entities from the web.

The search function, the list view and the graphic navigation give you optimal access to your knowledge.

mindlib saves your mind maps locally and synchronizes them with a server. So your knowledge management is always available - even when you are offline.

The app supports the OPML format for importing and exporting information. This enables the exchange with other applications and the creation of backups.

Use the web version to open mindlib from the desktop 

Site: (mindlib.de).

### App Store link:
https://apps.apple.com/de/app/mindlib/id1522257352

**Comment by brettkromkamp** [comment]
Added!
